- name: catalogue
  hosts: catalogue
  become: yes
  tasks: 
  - name: disable and enable old nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install NodeJS
    ansible.builtin.dnf:
      name: nodejs
      start: present

  - name: Add application User
    ansible.builtin.user:
      name: roboshop
    
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the application code to created app directory
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes


